/**:
  ros__parameters:
    cmd_freq: 100.0  # Hz of platform commands send
    info_freq: 10.0  # Hz of platform info publish
    ipc_cmd_port: 15760  # UDP port for sending commands to Python runner
    ipc_tel_port: 15761  # UDP port for receiving telemetry from Python runner
    takeoff_altitude: 25.0  # Takeoff altitude in metres (min 25 on DT)
